name: Python Bindings
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  python_bindings:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-24.04, ubuntu-22.04, windows-2022, macos-14, macos-15] 
        os: [ubuntu-24.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v4
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Build with pip
        run: |
          python -m pip install --verbose ./python/
      - name: Test entrypoint
        run: |
          rko_lio --help
